apiVersion: apps/v1
kind: Deployment
metadata:
  name: invalid-selector-matchExpressions
spec:
  minReadySeconds: 10
  paused: false
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchExpressions:
<<<<<<< HEAD
      - operator: In          # Wrong
=======
      - operator: In          # 錯誤：缺少 key 欄位
>>>>>>> 34c8534f562dda0e041a17986549af9e8c003fe4
        values:
          - myapp
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: nginx:latest
