apiVersion: apps/v1
kind: Deployment
metadata:
  name: invalid-maxUnavailable
spec:
  minReadySeconds: 10
  paused: false
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
<<<<<<< HEAD
      maxUnavailable: [25]   # Wrong : should be int or string
=======
      maxUnavailable: [25]   # 錯誤：maxUnavailable 應為整數或字串，不可為陣列
>>>>>>> 34c8534f562dda0e041a17986549af9e8c003fe4
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: nginx:latest