apiVersion: apps/v1
kind: Deployment
metadata:
  name: invalid-strategy-rollingUpdate
spec:
  minReadySeconds: 10
  paused: false
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
    rollingUpdate: "should be an object"   # 錯誤：需提供物件格式，包含 maxSurge 與 maxUnavailable
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: nginx:latest
