apiVersion: apps/v1
kind: Deployment
metadata:
  name: invalid-paused
spec:
  minReadySeconds: 10
  paused: 1    # Wrong : should be boolen (true/false)
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: nginx:latest
