apiVersion: apps/v1
kind: Deployment
metadata:
  name: invalid-template
spec:
  minReadySeconds: 10
  paused: false
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  # Wrong : should contain template
